name: Automatic Deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Welcome
        run: echo Start deploying SenSwap API
      - name: Build Dockerfile
        run: |
          sed -i 's/__ENV__/prod/g' Dockerfile
          cat Dockerfile
      - name: Build docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tuphanson/senswap-api-mainnet
          tags: latest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Build ECS Task Definition
        run: |
          sed -i 's/__DBUSERNAME__/${{ secrets.DB_USERNAME_MAINNET }}/g' task-definition.json
          sed -i 's/__DBPASSWORD__/${{ secrets.DB_PASSWORD_MAINNET }}/g' task-definition.json
      - name: Update ECS Task Definition
        run: aws-actions/amazon-ecs-render-task-definition@v1
        task-definition: task-definition.json
        container-name: senswap-api-mainnet
        image: tuphanson/senswap-api-mainnet