name: Automatic Deployment

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Welcome
        run: echo Start deploying SenSwap API
      - name: Build Dockerfile
        run: |
          sed -i 's/__ENV__/stag/g' Dockerfile
          cat Dockerfile
      - name: Build docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tuphanson/senswap-api-testnet
          tags: latest
      - name: Run docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_TESTNET }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATEKEY_TESTNET }}
          script: |
            sudo docker stop api
            sudo docker rm api
            sudo docker pull tuphanson/senswap-api-testnet
            sudo docker run -d -p 80:80 --name api tuphanson/senswap-api-testnet
            sudo docker image prune -a -f
            echo "{\"username\":\"${{ secrets.DB_USERNAME_TESTNET }}\",\"password\":\"${{ secrets.DB_PASSWORD_TESTNET }}\",\"dbname\":\"senswap-api\"}" >> atlas.json
            sudo docker cp ./atlas.json api:/home/senswap-api/configs/credential/atlas.json
            rm -rf atlas.json
